export enum BackendCapability {

    FILESYSTEM = "FILESYSTEM",

    CODE_GENERATION = "CODE_GENERATION",

    CODE_ANALYSIS = "CODE_ANALYSIS",

    DOCUMENT_GENERATION = "DOCUMENT_GENERATION",

    COMMAND_EXECUTION = "COMMAND_EXECUTION",

    TOOL_USE = "TOOL_USE",

    STREAMING = "STREAMING",

}