export enum EngineeringArtifactType {

    MARKDOWN_REQUIREMENTS =
        "MARKDOWN_REQUIREMENTS",

    REQUIREMENTS =
        "REQUIREMENTS",

    VALIDATED_REQUIREMENTS =
        "VALIDATED_REQUIREMENTS",

    REQUIREMENT_SET =
        "REQUIREMENT_SET",

    VALIDATED_REQUIREMENT_SET =
        "VALIDATED_REQUIREMENT_SET",

    REQUIREMENTS_DOCUMENT =
        "REQUIREMENTS_DOCUMENT",

    KNOWLEDGE_FINDINGS =
        "KNOWLEDGE_FINDINGS",

    KNOWLEDGE_SYNTHESIS =
        "KNOWLEDGE_SYNTHESIS",

    RESEARCH_SOURCE =
        "RESEARCH_SOURCE",

    RESEARCH_GAPS =
        "RESEARCH_GAPS",

    DOMAIN_MODEL =
        "DOMAIN_MODEL",

    ARCHITECTURE =
        "ARCHITECTURE",

    PERSISTENCE_MODEL =
        "PERSISTENCE_MODEL",

    API_CONTRACT =
        "API_CONTRACT",

    BACKEND =
        "BACKEND",

    FRONTEND =
        "FRONTEND",

}