export enum EngineeringArtifactType {

    MARKDOWN_REQUIREMENTS = "MARKDOWN_REQUIREMENTS",

    REQUIREMENTS = "REQUIREMENTS",

    DOMAIN_MODEL = "DOMAIN_MODEL",

    ARCHITECTURE = "ARCHITECTURE",

    PERSISTENCE_MODEL = "PERSISTENCE_MODEL",

    API_CONTRACT = "API_CONTRACT",

    BACKEND = "BACKEND",

    FRONTEND = "FRONTEND",

}